---
- name: Install default packages
  hosts: localhost
  connection: local

  tasks:
  - name: Load variables
    ansible.builtin.include_vars: "{{ ansible_hostname }}.yaml"
  - name: Install modules
    ansible.builtin.include_tasks: tasks/{{ task }}.yaml
    loop:
    - init
    - envvars
    - bash_completion
    - git
    - jq
    - docker
    - google_chrome
    - vscode
    - loganmzz-scripts
    - jdks
    - nvm
    - rust
    - slack
    - kubectl
    - helm
    - terraform
    - google-cloud-sdk
    - starship
    - discord
    - aws
    - chromium
    - apache-maven
    - jetbrains
    - golang
    - spotify
    - azure
    when: 'task not in (disabled_tasks | default([])) and (enabled_tasks is not defined or task in enabled_tasks)'
    loop_control:
      loop_var: task
