---
- name: Install default packages
  hosts: localhost

  tasks:
  - name: Temporary directory
    ansible.builtin.file:
      path: ./temp
      state: directory
      mode: u=rwx,g=,o=
  - name: Directory ~/.local
    ansible.builtin.file:
      path: "~/{{ item }}"
      state: directory
      mode: u=rwx,g=rx,o=
    loop:
    - .local
    - .local/bin
    - .local/lib
    - .local/etc

  - ansible.builtin.include_tasks: tasks/{{ task }}.yaml
    loop:
    - envvars
    - bash_completion
    - git
    - google_chrome
    - vscode
    - loganmzz-scripts
    - jdks
    - nvm
    - slack
    - kubectl
    loop_control:
      loop_var: task
