---
- name: Install default packages
  hosts: localhost

  tasks:
  - name: Temporary directory
    ansible.builtin.file:
      path: ./temp
      state: directory
      mode: u=rwx,g=,o=
  - name: Directory ~/.local
    ansible.builtin.file:
      path: "~/{{ item }}"
      state: directory
      mode: u=rwx,g=rx,o=
    loop:
    - .local
    - .local/bin
    - .local/lib
    - .local/etc

  - name: Setup Git
    ansible.builtin.include_tasks: tasks/git.yaml

  - name: Install Google Chrome
    ansible.builtin.include_tasks: tasks/google_chrome.yaml

  - name: Install VS Code
    ansible.builtin.include_tasks: tasks/vscode.yaml

  - name: Install loganmzz-scripts
    ansible.builtin.include_tasks: tasks/loganmzz-scripts.yaml
