---
- name: Install default packages
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - ansible.builtin.include_tasks: tasks/{{ task }}.yaml
    loop:
    - init
    - envvars
    - bash_completion
    - git
    - jq
    - google_chrome
    - vscode
    - loganmzz-scripts
    - jdks
    - nvm
    - slack
    - kubectl
    - helm
    - terraform
    - google-cloud-sdk
    loop_control:
      loop_var: task
