- name: Install asdf | git clone
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.14.0
    depth: 1
    force: true
    single_branch: true

- name: Install asdf | envvars
  ansible.builtin.copy:
    src: ./files/asdf/envvars.shrc
    dest: ~/.local/etc/envvars/10-asdf.shrc

- name: Install asdf | Bash completion
  ansible.builtin.copy:
    src: ./files/asdf/bash_completion.shrc
    dest: ~/.local/etc/bash_completion.d/asdf
