- name: Install bash_completion | Script
  ansible.builtin.copy:
    src: ./files/bash_completion/main.shrc
    dest: ~/.bash_completion
    backup: yes

- name: Install bash_completion | Directory
  ansible.builtin.file:
    path: ~/.local/etc/bash_completion.d
    state: directory
