- vars:
    discord_version: 0.0.21
  block:
  - name: Install Discord | Download
    ansible.builtin.get_url:
      url: "https://dl.discordapp.net/apps/linux/{{ discord_version }}/discord-{{ discord_version }}.deb"
      dest: ./temp/discord.deb
    when: not discord_version in (ansible_facts.packages.discord | default([]) | map(attribute='version'))

  - name: Install Discord | Install
    become: yes
    ansible.builtin.apt:
      deb: ./temp/discord.deb
    when: not discord_version in (ansible_facts.packages.discord | default([]) | map(attribute='version'))

  - name: Install Discord | Clear
    ansible.builtin.file:
      path: ./temp/discord.deb
      state: absent
