- name: Install envvars | Config directory
  ansible.builtin.file:
    path: ~/.local/etc/envvars
    state: directory

- name: Install envvars | Main script
  ansible.builtin.copy:
    src: ./files/envvars/main.shrc
    dest: ~/.envvars
    backup: yes

- name: Install envvars | Setup .bashrc
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    insertbefore: BOF
    marker: "# {mark} envvars"
    block: |
      . ~/.envvars
