- name: Install Google Cloud CLI | Check
  ansible.builtin.command: gcloud --version
  ignore_errors: yes
  changed_when: False
  register: gcloud_check_bin

- debug:
    msg: "{{ gcloud_check_bin.stdout_lines | select('match', '^Google Cloud SDK [^ ]+$') }}"

- vars:
    google_cloud_sdk:
      version:
        # https://cloud.google.com/sdk/docs/release-notes
        expected: "403.0.0"
        actual: "{{ gcloud_check_bin.stdout_lines | select('match', '^Google Cloud SDK [^ ]+$') | first | regex_replace('Google Cloud SDK ', '') }}"
    google_cloud_sdk_archive: "{{ playbook_dir }}/temp/google-cloud-sdk-{{ google_cloud_sdk.version.expected }}.tar.gz"
  block:
  - name: Install Google Cloud CLI | Check
    debug:
      var: google_cloud_sdk.version

  - name: Install Google Cloud CLI | Check
    ansible.builtin.stat:
      path: ~/.local/lib/google-cloud-sdk
    register: google_cloud_sdk_dir_check

  - name: Install Google Cloud CLI | Download
    ansible.builtin.get_url:
      url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-{{ google_cloud_sdk.version.expected }}-linux-x86_64.tar.gz
      dest: "{{ google_cloud_sdk_archive }}"
    when: google_cloud_sdk_dir_check.stat.exists == False

  - name: Install Google Cloud CLI | Extract
    ansible.builtin.unarchive:
      src: "{{ google_cloud_sdk_archive }}"
      dest: "~/.local/lib"
    when: google_cloud_sdk_dir_check.stat.exists == False

  - name: Install Google Cloud CLI | path
    ansible.builtin.file:
      path: "~/.local/etc/envvars/00-glcoud-sdk.shrc"
      src: ~/.local/lib/google-cloud-sdk/path.bash.inc
      state: link

  - name: Install Google Cloud CLI | bash_completion
    ansible.builtin.file:
      path: "~/.local/etc/bash_completion.d/google-cloud-sdk"
      src: ~/.local/lib/google-cloud-sdk/completion.bash.inc
      state: link

  - name: Install Google Cloud CLI | Components
    loganmzz_gcloud_component:
      name: "{{ item }}"
    loop:
    - gke-gcloud-auth-plugin

  - name: Install Google Cloud CLI | Clear
    ansible.builtin.file:
      path: "{{ google_cloud_sdk_archive }}"
      state: absent
