- name: Install Google Chrome | apt_source
  become: yes
  ansible.builtin.apt_repository:
    filename: google-chrome
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main

- name: Install Google Chrome | apt_key
  become: yes
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Install Google Chrome | apt
  become: yes
  ansible.builtin.apt:
    name:
    - google-chrome-stable
    state: latest
