- name: Install jq | Check
  ansible.builtin.command: jq --version
  ignore_errors: yes
  changed_when: False
  register: jq_check_bin

- vars:
    jq:
      version:
        expected: "1.6"
        actual: "{{ jq_check_bin.stdout_lines | first | default('') | regex_replace('^jq-', '') }}"
  block:
  - name: Install jq  | Check
    debug:
      var: jq.version

  - name: Install jq | Download
    ansible.builtin.get_url:
      url: https://github.com/stedolan/jq/releases/download/jq-{{ jq_version }}/jq-linux64
      dest: ~/.local/bin/jq
      mode: u=rwx,g=rx,o=
    when: jq.version.expected != jq.version.actual

  - name: Install jq | bash_completion
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/scop/bash-completion/master/completions/jq
      dest: ~/.local/etc/bash_completion.d/jq
      mode: u=rw,g=r,o=
