- name: Install kubectl | Check
  ansible.builtin.command: kubectl version --short --client
  ignore_errors: yes
  changed_when: False
  register: kubectl_check_bin

- vars:
    kubectl:
      version:
        expected: "v1.24.4"
        actual: "{{ kubectl_check_bin.stdout_lines | first | default('') | regex_replace('^Client Version: ', '') }}"
  block:
  - name: Install kubectl | Check
    debug:
      var: kubectl.version

  - name: Install kubectl | kubectl - Download
    ansible.builtin.get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl.version.expected }}/bin/linux/amd64/kubectl
      dest: ~/.local/bin/kubectl
      mode: u=rwx,g=rx,o=
      force: yes
    when: kubectl.version.expected != kubectl.version.actual

- name: Install kubectl | kubectx/kubens - Git clone
  ansible.builtin.git:
    repo: https://github.com/ahmetb/kubectx
    dest: ~/.local/lib/kubectx
    single_branch: yes

- name: Install kubectl | kubectx/kubens - Link binaries
  ansible.builtin.file:
    src: "~/.local/lib/kubectx/{{ item }}"
    dest: "~/.local/bin/{{ item }}"
    state: link
  loop:
  - kubectx
  - kubens

- name: Install kubectl | kubectl - bash_completion
  ansible.builtin.copy:
    src: ./files/kubectl/bash_completion.shrc
    dest: ~/.local/etc/bash_completion.d/kubectl

- name: Install kubectl | kubectl - envvars
  ansible.builtin.copy:
    src: ./files/kubectl/kubectl_envvars.shrc
    dest: ~/.local/etc/envvars/00-kubectl.shrc

- name: Install kubectl | kubectx/kubens - Link bash_completion
  ansible.builtin.file:
    src: "~/.local/lib/kubectx/completion/{{ item }}.bash"
    dest: "~/.local/etc/bash_completion.d/{{ item }}"
    state: link
  loop:
  - kubectx
  - kubens

- name: Install kubectl | krew - Check
  ansible.builtin.stat:
    path: ~/.krew/bin/kubectl-krew
  register: kubectl_krew_bin_check

- name: Install kubectl | krew - Download
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-linux_amd64.tar.gz
    dest: ./temp/kubectl-krew.tar.gz
  when: kubectl_krew_bin_check.stat.exists == False

- name: Install kubectl | krew - Extract
  ansible.builtin.file:
    path: temp/kubectl-krew
    state: directory
  when: kubectl_krew_bin_check.stat.exists == False

- name: Install kubectl | krew - Extract
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/temp/kubectl-krew.tar.gz"
    dest: "{{ playbook_dir }}/temp/kubectl-krew"
  when: kubectl_krew_bin_check.stat.exists == False

- name: Install kubectl | krew - Install
  ansible.builtin.copy:
    src: ./temp/kubectl-krew/krew-linux_amd64
    dest: ~/.local/bin/krew
  when: kubectl_krew_bin_check.stat.exists == False

- name: Install kubectl | krew - Install
  ansible.builtin.command: ./temp/kubectl-krew/krew-linux_amd64 install krew
  when: kubectl_krew_bin_check.stat.exists == False

- name: Install kubectl | krew - Clear
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
  - ./temp/kubectl-krew
  - ./temp/kubectl-krew.tar.gz

- name: Install kubectl | krew - envvars
  ansible.builtin.copy:
    src: ./files/kubectl/krew_envvars.shrc
    dest: ~/.local/etc/envvars/00-kubectl-krew.shrc

- name: Install kubectl | krew - Plugins
  loganmzz_krew:
    name: "{{ item }}"
  loop:
  - whoami
  - deprecations
