- name: Install nvm | git clone
  ansible.builtin.git:
    repo: git@github.com:nvm-sh/nvm.git
    dest: ~/.nvm
    version: v0.39.7

- name: Install nvm | envvars
  ansible.builtin.copy:
    src: ./files/nvm/envvars.shrc
    dest: ~/.local/etc/envvars/00-nvm.shrc
    remote_src: yes

- name: Install nvm | default-packages
  ansible.builtin.copy:
    src: ./files/nvm/default-packages
    dest: ~/.nvm/
    remote_src: yes
    backup: yes
