- vars:
    slack:
      # https://slack.com/intl/fr-fr/release-notes/linux
      version: '4.28.171'
  block:
  - name: Install Slack | Check
    ansible.builtin.shell: type slack
    ignore_errors: yes
    changed_when: False
    register: slack_bin_check

  - name: Install Slack | Download
    ansible.builtin.get_url:
      url: "https://downloads.slack-edge.com/releases/linux/{{ slack.version }}/prod/x64/slack-desktop-{{ slack.version }}-amd64.deb"
      dest: ./temp/slack.deb
      mode: '0640'
    when: slack_bin_check is failed

  - name: Install Slack | apt
    become: yes
    become_user: root
    ansible.builtin.apt:
      deb: ./temp/slack.deb
    when: slack_bin_check is failed

  - name: Install Slack | Clear
    ansible.builtin.file:
      path: ./temp/slack.deb
      state: absent
