- name: Install VS Code | Compute path
  ansible.builtin.set_fact:
    vscode_user_config_path: ~/.config/Code/User

- name: Install VS Code | Compute path
  ansible.builtin.shell:
    cmd: "wslpath \"$(wslvar APPDATA)\""
  when: "lookup('ansible.builtin.env', 'WSL_DISTRO_NAME') | default('') != ''"
  register: vscode_wsl_appdata

- name: Install VS Code | Compute path
  ansible.builtin.set_fact:
    vscode_user_config_path: "{{ vscode_wsl_appdata.stdout | trim }}/Code/User"
  when: vscode_wsl_appdata.changed

# https://code.visualstudio.com/updates/
- name: Install VS Code | Check
  ansible.builtin.command: code --version
  ignore_errors: yes
  changed_when: False
  register: vscode_bin_check

- vars:
    vscode:
      version:
        expected: "1.88.1"
        actual: "{{ vscode_bin_check.stdout_lines | first | default('') }}"
  block:
  - name: Install VS Code | Check
    debug:
      var: vscode.version

  - name: Install VS Code | Download
    ansible.builtin.get_url:
      url: https://update.code.visualstudio.com/{{ vscode.version.expected }}/linux-deb-x64/stable
      dest: ./temp/vscode.deb
      mode: '0640'
    when: vscode.install | default(True) and vscode.version.expected != vscode.version.actual

  - name: Install VS Code | apt
    become: yes
    become_user: root
    ansible.builtin.apt:
      deb: ./temp/vscode.deb
    when: vscode.install | default(True) and vscode.version.expected != vscode.version.actual

  - name: Install VS Code | Clear
    ansible.builtin.file:
      path: ./temp/vscode.deb
      state: absent

- name: Install VS Code | Copy user settings
  ansible.builtin.copy:
    src: ./files/vscode/config/settings.json
    dest: "{{ vscode_user_config_path }}/settings.json"
    mode: '0640'
    backup: yes

- name: Install VS Code | Copy user keybindings
  ansible.builtin.copy:
    src: ./files/vscode/config/keybindings.json
    dest: "{{ vscode_user_config_path }}/keybindings.json"
    mode: '0640'
    backup: yes

- name: Install VS Code | Copy user snippets
  ansible.builtin.file:
    path: "{{ vscode_user_config_path }}/snippets/"
    state: directory

- name: Install VS Code | Copy user snippets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ vscode_user_config_path }}/snippets/"
    backup: yes
  with_fileglob:
    - ./files/vscode/config/snippets/*.json
  loop_control:
    label: "{{ item | basename }}"

- name: Install VS Code | envvars
  ansible.builtin.copy:
    src: ./files/vscode/envvars.shrc
    dest: ~/.local/etc/envvars/00-vscode.shrc

- name: Install VS Code | Extensions
  loganmzz_vscode_extension:
    name: "{{ item }}"
  loop:
  - bierner.emojisense
  - bierner.markdown-mermaid
  - eamodio.gitlens
  - golang.go
  - hashicorp.terraform
  - hookyqr.beautify
  - killsen.openresty-nginx-conf
  - ms-python.python
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - redhat.ansible
  - rust-lang.rust-analyzer
  - serayuzgur.crates
  - tamasfe.even-better-toml
