- name: Install VS Code | Download
  ansible.builtin.get_url:
    url: https://update.code.visualstudio.com/1.70.2/linux-deb-x64/stable
    dest: ./temp/vscode-1.70.2.deb
    mode: '0640'

- name: Install VS Code | apt
  become: yes
  become_user: root
  ansible.builtin.apt:
    deb: ./temp/vscode-1.70.2.deb

- name: Install VS Code | Copy user settings
  ansible.builtin.copy:
    src: ./files/vscode/settings.json
    dest: ~/.config/Code/User/settings.json
    mode: '0640'
    backup: yes

- name: Install VS Code | Copy user keybindings
  ansible.builtin.copy:
    src: ./files/vscode/keybindings.json
    dest: ~/.config/Code/User/keybindings.json
    mode: '0640'
    backup: yes

- name: Install VS Code | Copy user snippets
  ansible.builtin.file:
    path: ~/.config/Code/User/snippets/
    state: directory

- name: Install VS Code | Copy user snippets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/Code/User/snippets/
    backup: yes
  with_fileglob:
    - ./files/vscode/snippets/*.json
  loop_control:
    label: "{{ item | basename }}"

- name: Install VS Code | Extensions
  loganmzz_vscode_extension:
    name: "{{ item }}"
  loop:
  - eamodio.gitlens
  - ms-python.python
  - hashicorp.terraform
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - hookyqr.beautify
